### PR TITLE
Header component

### LINKED ISSUE #13: React: Header
This ticket provides the Header component as illustrated in the HTML prototypes. 
https://seas-computing.github.io/directory-screens-prototype/home.html

The scope of this component is limited what is shown in the screenshot attached.

Screen Shot 2021-07-30 at 3 01 40 PM

This header is show on both the "Welcome" screen and the results screen.

### PR DESCRIPTION
**Pull request by jonseitz**
This PR creates a Header component in our app that mirrors the design of the header from our prototype. Since we'll always be displaying this app on the same hardware (1920x1080 displays), I've used a number of hard-coded width/height values and left out `@media` queries for responsiveness.

To view the output, run `npm run start` and open localhost:3000. I'd recommend using the developer tools responsive mode and setting a fixed width/height to see roughly how it will look in portrait mode. 

This PR includes no tests, since we're essentially rendering static content.

Fixes #13

### CODE REVIEW

**Comment by chrxr** [comment]
Thanks @jonseitz . Looking at the prototype, at the largest media query we have the banner centered, the same width as the "Welcome" text box below it, whereas here the banner reaches to the edge of the screen on the right. I think this may be because it is being based on the slightly smaller screen media query in the prototype. Personally I prefer the centered version with equal whitespace on both sides for the banner. @Vittorio2015, what do you think?

Screen Shot 2021-08-12 at 9 20 21 AM

**Comment by Vittorio2015** [comment]
@chrxr and @jonseitz , I agree that the non-bleed option is best, especially if the rest of the interface (i.e., search results) are aligned within boundaries defined by the left and right edge of the banner and welcome elements.
Shall we follow the same criteria for the horizontal boundaries and alignment of the footer (so that it also doesn't bleed, as it currently does on the prototype)?

image

**Comment by jonseitz** [comment]
@Vittorio2015 I'm good without the bleed on the Header, though the current footer design may look a little odd if it doesn't bleed all the way to the edge. We might want to mock that up first to be sure.

Just to clarify a little about how I'm going about building this: I'm approaching this less as a _web page_ and more as an _appliance interface_ (where the use of web technologies is just an underlying implementation detail). As far as I've been told, this interface will **only** be viewed on a 1080x1920 55" display, so I've been ignoring all the `@media` queries and dynamic resizing features and only building for that _exact_ size using the device emulation mode built into Firefox. (If that's not correct let's talk about it now so I can change my approach before we get to far along).

I raise this only because the full size screen shots that have been posted here have been done on higher-resolution displays (looks like 2560x1440) so bootstrap's built-in responsive features are rendering things differently because all the `@media` queries use pixel values. **Is the design of that larger rendering what we should be building for instead?**

Just for reference, [here's the relevant spec sheet][specs] for the displays (some back-of-the-envelope math says our pixel density is just about 38.75 ppi):




[specs]: https://www.planar.com/products/large-format-displays/ps4k/planar-ps5561t/

**Comment by natalynyu** [comment]
@jonseitz I agree, I think it may look a bit odd if the footer doesn't bleed to the edge. The users might think that they are not zoomed in all the way and try to zoom in if both the header and footer have whitespace surrounding them.

**Comment by jonseitz** [comment]
@Vittorio2015 @chrxr @natalynyu I've been working on the "Main" section and tried implementing the non-bleed header along with the full welcome message, seen here at 1080x1920:

Screen Shot 2021-08-13 at 10 40 35

To give some sense of how this would scale on the 55" display:

 - The left and right margins would be just over 1.5 inches wide (60px @ 38.75ppi)
 - The "Touch anywhere ..." text would be about 2.5 inches tall (96px @ 38.75ppi)
 - The SEAS logo at the top would be just under 1.5 inches tall (55px @ 38.75ppi)
 - The banner photo would be nearly six inches tall (262px @ 38.75ppi)

Does this work as a happy medium?

**Comment by chrxr** [comment]
@jonseitz I think this looks great. Thanks for working on this.

**Comment by Vittorio2015** [comment]
@natalynyu and @jonseitz , I'll mock up the footer to match the left and right margin of the branding and "welcome" message. I just assume that users will not try to zoom in since the instructions specifically refer to (1) touch anywhere on the monitor... and (2) interact with the keyboard. Ultimately, user testing will clarify our assumptions.
In any case, I have been using a SEAS footer with a margin on numerous OpenScholar websites (see [PhD Open House](https://openhouse.seas.harvard.edu/#boxes-box-1610381724) as an example) and I have never experienced users' need for zooming in.

With regard to [@jonseitz information on the display](https://github.com/seas-computing/sec-directory-client/pull/16#issuecomment-898450132), (and @chrxr shall confirm this), this interface will only be displayed and interacted with on specific displays at 114 and SEC. Therefore we should disregard any media queries for responsiveness (display on other devices) or any responsive code (i.e.: Bootstrap) I employed for design mockups, which unfortunately could never be tested on the specific displays during the design stage.

**Comment by chrxr** [comment]
To be clear, I personally like the full bleed footer and the header with the margins, as @jonseitz has mocked up here. However, I am not that attached to it, so if you folks think otherwise that's fine with me. 

@Vittorio2015 Yes, there should be no need to worry about either users zooming in, or media queries, as this will only be displayed on the very specific screen size.

**Review by natalynyu — APPROVED** [review]
All looks great to me! Approved.

**Pull request merged**
